### ISSUE TITLE
[Request] Adding password bruteforce and directory fuzzing option

### ISSUE THREAD

**Issue by an0th3rhuman** [jaeles-project/jaeles#11]
Send the request from brup to Jaeles. And use jaeles to brute force password or fuzz directories.

Why we need to do that?

1. Since jaeles is written in go, it will be faster
2. Burp intruder cant manage large file such as rockyou.txt for brute forcing , the burp will be crashed.(In my vm :( . dont know about other system)

**Comment by j3ssie** [comment]
You can actually do it with variables. But you will need the format of the request first.
For example, this is a signature brute force for **grafana** login panel.

```yaml
# info to search signature
id: cred-grafana-01
info:
  name: Grafana default credentials
  risk: High

variables:
  - pass: |
      admin
      123456
      password

requests:
  - method: POST
    redirect: false
    url: >-
      {{.BaseURL}}/login
    headers:
      - User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:55.0) Gecko/20100101 Firefox/55
      - Content-Type: application/json
      - Referer: "{{.BaseURL}}/login"
    body: '{"user":"admin","email":"","password":"{{.pass}}"}'
    detections:
      - >-
        StatusCode() == 200 && !StringSearch("response", "Logged in") && StringSearch("resHeaders", "grafana_session=")


```
