### ISSUE TITLE
Missing hability to modify original parameter name

### ISSUE THREAD

**Issue by ElSicarius** [jaeles-project/jaeles#29]
Hello,

I might have missed something but it looks like we can't modify the **original** parameters names by using generators.

For example: What I would like to automate: 
hxxps://test.com/index.php?test1=aaa&test2=aaaa -> hxxps://test.com/index.php?test1[]=aaa&test2[]=aaaa

Did I missed something or this would be an awesome functionnality to add ? 😁

Regards,

**Comment by j3ssie** [comment]
Currently, Jaeles doesn't have a direct func to replace that but you can work around with this one https://jaeles-project.github.io/signatures/generator/#replace-fuzz

**Comment by ElSicarius** [comment]
I did something a bit different, it works fine :) :
```yaml
variables:
  - name: InputCmd('echo "{{.RawQuery}}" | tr "&" "\n" | sed -E "s/=.*//"')

requests:
  - generators:
      - Query("[[.original]]","{{.name}}[]")
```

Thanks !
